### ISSUE TITLE
documentation error for granting anonymous users access

### ISSUE THREAD

**Issue by mjkubba** [awsdocs/amazon-s3-userguide#109]
For anonymous users, the following elements are equivalent
```
"Principal": "*"
"Principal" : { "AWS" : "*" }
```
This doc stating otherwise: https://github.com/awsdocs/amazon-s3-userguide/blob/main/doc_source/s3-bucket-user-policy-specifying-principal-intro.md
Tested and validated that both allow curl/browser (https://) as well as aws s3 cp (s3://) if you specify `"Principal" : { "AWS" : "*" }`

**Comment by aws-alan** [comment]
Hello, which lines are you seeing this stated otherwise? On the linked page I see the following:
"For anonymous users, these two methods are equivalent."

**Comment by mjkubba** [comment]
Hi Alan
This part:
```
Because anyone can create an AWS account, the security level of these two methods is equivalent, even though they function differently.
```
In reality, you don't even need AWS account, tested with a browser in private mode and still worked,
The proper way of blocking this access to non-AWS users is to add a Condition:
`"Condition": { "Null": { "aws:PrincipalArn": false}}`

Edit: if you want to discuss this more internally my ID: mjkubba@

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
