### ISSUE TITLE
No option available to create S3 specific cost and usage report

### ISSUE THREAD

**Issue by robgero** [awsdocs/amazon-s3-userguide#111]
Following the guide from the snippet below, I've gotten this far, but I don't have the option to select `Services` for my report.

https://github.com/awsdocs/amazon-s3-userguide/blob/c156d50a2c699555db488e1bd3a239d125ea261f/doc_source/aws-usage-report.md?plain=1#L49

I created a report with default settings which included some S3 API calls, but I don't think it included all, or it doesn't have the granularity I was looking for. I need to get the egress cost per IAM user.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
