### ISSUE TITLE
S3 CORS configs must now be in JSON - need to remove the XML example

### ISSUE THREAD

**Issue by gherlein** [awsdocs/amazon-s3-userguide#13]
Attempting to use XML returns an error "The CORS configuration must be written in valid JSON."

The docs should not show an example of using XML.

**Comment by lincolahanbeck** [comment]
Hello,

I've updated the CORS documentation to clarify that the S3 console only takes JSON CORS configurations. You'll also notice that the CORS page now defaults to the JSON examples upon load:

[Creating a cross-origin resource sharing (CORS) configuration](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ManageCorsUsing.html)

Thank you for taking the time to submit this issue. We appreciate your feedback.

Lindsay
