### ISSUE TITLE
Announcements about S3 BitTorrent discontinuation shouldn't be buried in the commit history

### ISSUE THREAD

**Issue by alexwlchan** [awsdocs/amazon-s3-userguide#27]
Commit 0d17598 (13 May) announced the deprecation plan for S3 BitTorrent:

```diff
# doc_source/S3Torrent.md
+ As of April 29, 2021 Amazon S3 is discontinuing the S3 BitTorrent feature and it will no
+ longer be available to enable\. AWS will support customers currently using the
+ S3 BitTorrent feature for 12 months\. After April 29, 2022, BitTorrent clients will
+ no longer connect to Amazon S3\.
```

The entire page was then removed in commit 7a83e40 (19 May).

At present, the discontinuation notice doesn't appear anywhere in the S3 documentation; all mention of BitTorrent has been completely removed. If somebody is wondering if this feature is still supported or for how much longer it'll be available, that's pretty difficult to find right now.

It would be helpful if there was a page with this warning as part of the S3 documentation, so people could find this information more easily than poking through the commit history.

**Comment by scottpedia** [comment]
@alexwlchan 

Hello

But it seems to me that still the official docs site doesn't cover the deprecation at all. In addition, there is a misleading article that talks about how to get the torrent for a specific object, which you can find [here](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectTorrent.html). We need to remove similar misleading articles and possibly add permanent notice on the site to tell developers not to use this deprecated service.

**Comment by scottpedia** [comment]
@alexwlchan 

Is it possible that the AWS changed its mind between May 13 and 19, and retracted the announcement?

**Comment by alexwlchan** [comment]
> there is a misleading article that talks about how to get the torrent for a specific object, which you can find here. We need to remove similar misleading articles

I don't think that's too misleading, it's describing how to use the S3 BitTorrent APIs – which will presumably continue to work until next April.

> and possibly add permanent notice on the site to tell developers not to use this deprecated service.

Yes, that's what I'm asking for.

> Is it possible that the AWS changed its mind between May 13 and 19, and retracted the announcement?

I'd be very surprised if they did, and if they did, I'd expect them to have restored the feature page for S3 BitTorrent.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
