### ISSUE TITLE
Host Zone

### ISSUE THREAD

**Issue by tautme** [awsdocs/amazon-s3-userguide#29]
I followed the instructions and the Route 53 domain does not link to S3 bucket. The S3 bucket endpoint works, but the domain doesn't. http://gypsyparadise.io.s3-website-us-east-1.amazonaws.com

The only missing part I found, was "create host zone."

 1. Select "Create host zone"
 1. Enter domain name in box
 1. leave default "public hosted zone" selected
 1. Finish by selecting "Create host zone" at bottom

Could someone help me with this?

I will add to instructions if this is correct.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
