### ISSUE TITLE
S3 Event Notifications on object version/deletemarker delete

### ISSUE THREAD

**Issue by gorj-tessella** [awsdocs/amazon-s3-userguide#44]
The documentation covers what events are generated when the content changes on unversioned s3 buckets, but doesn't document what events if any are generated when a prior version becomes current due to the deletion of the current version (or for that matter, what events are generated when prior versions are deleted). 

https://github.com/awsdocs/amazon-s3-userguide/blob/c824a324b8396257ec66c3cd09e99f9f2f76a5c9/doc_source/NotificationHowTo.md#L10-L17

https://github.com/awsdocs/amazon-s3-userguide/blob/c824a324b8396257ec66c3cd09e99f9f2f76a5c9/doc_source/DeletingObjectVersions.md#L1

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
