### ISSUE TITLE
question about bucket inventory

### ISSUE THREAD

**Issue by kisscelia** [awsdocs/amazon-s3-userguide#47]
Hi, if i set isEnabled to false when i make a put-bucket-inventory request, will the inventory be generated?

or generate a empty inventory?

and the last question is: can i get the inventory(isEnabled = false)'s detail info when i use get-bucket-inventory api?

thanks.

**Comment by kisscelia** [comment]
@xualber hi, any results?  thank you.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
