### ISSUE TITLE
Are upload limits in GB or GiB?

### ISSUE THREAD

**Issue by c0state** [awsdocs/amazon-s3-userguide#58]
https://github.com/awsdocs/amazon-s3-userguide/blob/main/doc_source/upload-objects.md specifies everything in GB for simple upload but the multi-part doc https://github.com/awsdocs/amazon-s3-userguide/blob/main/doc_source/qfacts.md uses GiB/TiB for everything.

**Comment by ChikangaTakudzwa** [comment]
The main difference between the two is that GB uses base 10 (decimal) arithmetic, while GiB uses base 2 (binary) arithmetic

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
