### ISSUE TITLE
Role missing some authorization for replication

### ISSUE THREAD

**Issue by clercrobin** [awsdocs/amazon-s3-userguide#59]
Hello, I followed this documentation: https://github.com/awsdocs/amazon-s3-userguide/blob/main/doc_source/replication-walkthrough1.md

However I did not to replicate my bucket. 

By adding s3:* in the policy of the IAM role it works. Do you know which action specifically I should add in this role ?

**Comment by aws-alan** [comment]
Hello,

Which IAM actions will depend on a number of factors (where you are replicating from, where you are replicating to, if you are replicating tags, etc). I'd recommend reviewing the following page for some basic examples.

https://github.com/awsdocs/amazon-s3-userguide/blob/main/doc_source/setting-repl-config-perm-overview.md
