### ISSUE TITLE
How to get users list who have access to s3 bucket

### ISSUE THREAD

**Issue by nomjitheegala** [awsdocs/amazon-s3-userguide#93]
I have created a policy with full control in S3. I want to read list of users/email address who can access designated s3 bucket?

When i used getBucketAcl it is throwing me my own permissions info (FULL_CONTROL).

List<String> bucketPermissions = s3Client.getBucketAcl(bucket.getName())
			.getGrantsAsList().stream().distinct()
			.map(t -> t.getPermission().toString())
			.collect(Collectors.toList());

Is there a way to read users list with S3 bucket access?

**Comment by cbcrowe** [comment]
First of all, apologies for the delayed response. I have forwarded your question to the S3 team and I hope to follow up with a response shortly. Thank you for submitting this Issue.

**Comment by nomjitheegala** [comment]
Thank you for your response.

In addition to that question how can we know what roles user has to a
particular bucket?

Thank you,
Nomji

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
