### ISSUE TITLE
Callback for receiving notification on a bucket

### ISSUE THREAD

**Issue by tedyu** [awsdocs/amazon-s3-userguide#94]
There is code under `EnableNotificationOnABucket` showing the usage of `SetBucketNotificationConfigurationRequest`.

I am looking for programmatic way of receiving notification on a bucket.
I searched the repository but haven't found such example.

Thanks

**Comment by cbcrowe** [comment]
Thank you for submitting this issue. A member of the team will be working on it and will provide updates here.

**Comment by aws-alan** [comment]
Hello, 

You can use S3 Event Notifications to receive messages for bucket actions. Such actions include: new object creation, object removal, restore objects, Replication & S3 Lifecycle events, and more. 

Please check out the following:
https://github.com/awsdocs/amazon-s3-userguide/blob/main/doc_source/NotificationHowTo.md
https://github.com/awsdocs/amazon-s3-userguide/blob/main/doc_source/enable-event-notifications.md

We are always working to improve our documentation, and your feedback helps us focus our efforts. If you are still having issues, you can also:

- Post your questions on the Amazon S3 discussion forum at https://forums.aws.amazon.com/
- Contact Technical Support at https://aws.amazon.com/contact-us

Thanks!
